# Generated by Django 4.1.2 on 2022-11-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
